# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gDfJvg4yTSYdY9QSGC55BgONT2xP7L8P
"""

while True:
    print("\nCalculadora Simples")

    # Recebe os dois números do usuário
    num1 = input("Digite o primeiro número: ")
    num2 = input("Digite o segundo número: ")

    # Converte os valores para float
    try:
        num1 = float(num1)
        num2 = float(num2)
    except ValueError:
        print("Erro: Por favor, digite números válidos.")
        continue

    # Menu de operações
    print("\nEscolha a operação desejada:")
    print("1 - Soma (+)")
    print("2 - Subtração (-)")
    print("3 - Multiplicação (*)")
    print("4 - Divisão (/)")

    opcao = input("Digite o número da operação: ")

    # Realiza a operação selecionada
    if opcao == '1':
        resultado = num1 + num2
        print(f"Resultado da soma: {resultado}")
    elif opcao == '2':
        resultado = num1 - num2
        print(f"Resultado da subtração: {resultado}")
    elif opcao == '3':
        resultado = num1 * num2
        print(f"Resultado da multiplicação: {resultado}")
    elif opcao == '4':
        if num2 != 0:
            resultado = num1 / num2
            print(f"Resultado da divisão: {resultado}")
        else:
            print("Erro: Divisão por zero não é permitida.")
    else:
        print("Opção inválida. Tente novamente.")

    # Verifica se o usuário quer continuar
    continuar = input("\nDeseja realizar outra operação? (s/n): ")
    if continuar.lower() != 's':
        print("Encerrando a calculadora. Até mais!")
        break